from fastapi import APIRouter, HTTPException, Depends
from bson import ObjectId
from app.database.mongodb import database
from app.core.security import get_current_user

import json
import httpx
from pathlib import Path


router = APIRouter(
    prefix="/api/videos",
    tags=["Videos"]
)


# ==========================================
# Generate Video from Uploaded PDF
# ==========================================

@router.post("/generate/{document_id}")
async def generate_video(
    document_id: str,
    current_user: dict = Depends(get_current_user)
):

    # ==========================================
    # 1. GET DOCUMENT
    # ==========================================

    try:
        document = await database.documents.find_one(
            {
                "_id": ObjectId(document_id),
                "user_id": current_user["user_id"]
            }
        )

    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Invalid document ID"
        )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found"
        )


    # ==========================================
    # 2. GET AI ANALYSIS
    # ==========================================

    analysis = document.get("analysis", {})

    if not analysis:
        raise HTTPException(
            status_code=400,
            detail="AI analysis not found for this document"
        )

    result = analysis.get("result", {})

    story_script = result.get("story_script", {})

    if not story_script:
        raise HTTPException(
            status_code=400,
            detail="AI story script not found"
        )

    scenes = story_script.get("scenes", [])

    if not scenes:
        raise HTTPException(
            status_code=400,
            detail="No video scenes generated by AI"
        )


    # ==========================================
    # 3. CREATE SCENE PLAN
    # ==========================================

    project_root = Path(__file__).resolve().parents[3]

    scene_plan_path = (
        project_root
        / "media_generation"
        / "final_pipeline"
        / "input"
        / "scene_plan.json"
    )

    scene_plan_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    scene_plan = {
        "title": story_script.get("title", "Educational Lesson"),
        "education_level": story_script.get("education_level", "General"),
        "language": story_script.get("language", "en"),
        "scenes": scenes
    }

    print(f"\n[VIDEO] document_id     : {document_id}")
    print(f"[VIDEO] filename        : {document.get('filename', 'unknown')}")
    print(f"[VIDEO] text_length     : {len(document.get('extracted_text', ''))}")
    print(f"[VIDEO] language        : {scene_plan['language']}")
    print(f"[VIDEO] education_level : {scene_plan['education_level']}")
    print(f"[VIDEO] title           : {scene_plan['title']}")
    print(f"[VIDEO] scene_count     : {len(scenes)}")
    for s in scenes[:5]:
        print(f"  Scene {s.get('scene_number')}: [{s.get('visual_type')}] {str(s.get('title',''))[:50]}")
        print(f"    narration: {str(s.get('narration',''))[:80]}...")
        print(f"    keywords : {s.get('keywords', [])}")


    # ==========================================
    # 4. SAVE SCENE PLAN
    # ==========================================

    try:

        with open(
            scene_plan_path,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                scene_plan,
                f,
                ensure_ascii=False,
                indent=2
            )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=f"Failed to create scene plan: {str(e)}"
        )


    # ==========================================
    # 5. CALL MEDIA ENGINE - 8003
    # ==========================================

    try:

        async with httpx.AsyncClient(
            timeout=1800.0
        ) as client:

            response = await client.post(
                "http://127.0.0.1:8003/generate-video"
            )

            response.raise_for_status()

            video_result = response.json()

    except httpx.HTTPError as e:

        raise HTTPException(
            status_code=500,
            detail=f"Media engine failed: {str(e)}"
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=f"Video generation failed: {str(e)}"
        )


    # ==========================================
    # 6. RETURN RESULT
    # ==========================================

    return {
        "message": "Video generated successfully",

        "document_id": document_id,

        "status": "generated",

        "scene_count": len(scenes),

        "video": video_result
    }


# ==========================================
# Stream Generated Video
# ==========================================

@router.get("/stream/{video_id}")
async def stream_video(
    video_id: str,
    current_user: dict = Depends(get_current_user)
):

    # NOTE:
    # This old GridFS streaming route is kept
    # for compatibility with existing videos.

    from io import BytesIO
    from fastapi.responses import StreamingResponse
    from app.database.mongodb import gridfs_bucket

    try:

        video = await database.videos.find_one(
            {
                "_id": ObjectId(video_id),
                "user_id": current_user["user_id"]
            }
        )

    except Exception:

        raise HTTPException(
            status_code=400,
            detail="Invalid video ID"
        )

    if not video:

        raise HTTPException(
            status_code=404,
            detail="Video not found"
        )

    try:

        grid_out = await gridfs_bucket.open_download_stream(
            ObjectId(video["video_file_id"])
        )

        video_data = await grid_out.read()

    except Exception:

        raise HTTPException(
            status_code=500,
            detail="Failed to load video"
        )

    return StreamingResponse(
        BytesIO(video_data),
        media_type="video/mp4"
    )


# ==========================================
# Get Video Details
# ==========================================

@router.get("/{video_id}")
async def get_video(
    video_id: str,
    current_user: dict = Depends(get_current_user)
):

    try:

        video = await database.videos.find_one(
            {
                "_id": ObjectId(video_id),
                "user_id": current_user["user_id"]
            }
        )

    except Exception:

        raise HTTPException(
            status_code=400,
            detail="Invalid video ID"
        )

    if not video:

        raise HTTPException(
            status_code=404,
            detail="Video not found"
        )

    video["video_id"] = str(video["_id"])

    del video["_id"]

    return video